// Auto-generated by generateComponentMap.js
import AddMaterialNote from './AddMaterialNote.jsx';
import AddProduct from './AddProduct.jsx';
import AddRole from './AddRole.jsx';
import AddUser from './AddUser.jsx';
import EditMaterialNote from './EditMaterialNote.jsx';
import EditProduct from './EditProduct.jsx';
import EditStoreAcceptance from './EditStoreAcceptance.jsx';
import Footer from './Footer.jsx';
import Header from './Header.jsx';
import HomePage from './HomePage.jsx';
import ListProducts from './ListProducts.jsx';
import LoginPage from './LoginPage.jsx';
import MaterialRecipt from './MaterialRecipt.jsx';
import PasswordChange from './PasswordChange.jsx';
import PrivateRoute from './PrivateRoute.jsx';
import ProductList from './ProductList.jsx';
import RoleMenuMapping from './RoleMenuMapping.jsx';
import Sidebar from './Sidebar.jsx';
import StoreAccComponent from './StoreAccComponent.jsx';
import SupplierRegistration from './SupplierRegistration.jsx';
import ViewMaterialNotePage from './ViewMaterialNotePage.jsx';
import ViewProduct from './ViewProduct.jsx';
import ViewStoreAcc from './ViewStoreAcc.jsx';
import ViewSupplierRegis from './ViewSupplierRegis.jsx';
import ViewUser from './ViewUser.jsx';

const componentsMap = {
  "AddMaterialNote": AddMaterialNote,
  "AddProduct": AddProduct,
  "AddRole": AddRole,
  "AddUser": AddUser,
  "EditMaterialNote": EditMaterialNote,
  "EditProduct": EditProduct,
  "EditStoreAcceptance": EditStoreAcceptance,
  "Footer": Footer,
  "Header": Header,
  "HomePage": HomePage,
  "ListProducts": ListProducts,
  "LoginPage": LoginPage,
  "MaterialRecipt": MaterialRecipt,
  "PasswordChange": PasswordChange,
  "PrivateRoute": PrivateRoute,
  "ProductList": ProductList,
  "RoleMenuMapping": RoleMenuMapping,
  "Sidebar": Sidebar,
  "StoreAccComponent": StoreAccComponent,
  "SupplierRegistration": SupplierRegistration,
  "ViewMaterialNotePage": ViewMaterialNotePage,
  "ViewProduct": ViewProduct,
  "ViewStoreAcc": ViewStoreAcc,
  "ViewSupplierRegis": ViewSupplierRegis,
  "ViewUser": ViewUser,
};

export default componentsMap;
